Repository mukesh-org/source-repo, pull requests merged in 2019-01, with the labels that each got.

#4 Update index.php
  html/index.php
Labels: size/XS

#5 Revert "Update index.php"
  html/index.php
Labels: approved, size/XS

#7 Revert "Revert "Update index.php""
  html/index.php
Labels: approved, size/XS

#9 Revert "Revert "Revert "Revert "Update index.php""""
  html/index.php
Labels: approved, size/XS

#10 Revert "Revert "Revert "Revert "Revert "Update index.php"""""
  html/index.php
Labels: approved, size/XS

#11 Revert "Revert "Revert "Revert "Revert "Revert "Update index.php""""""
  html/index.php
Labels: approved, size/XS

#16 Update index.php
  html/index.php
Labels: approved, lgtm, size/XS

#23 Prow test
  html/index.php
Labels: size/XS

#24 Update index.php
  html/index.php
Labels: ok-to-test, size/XS

#30 Development
  html/index.php
Labels: size/XS

#31 Update index.php
  html/index.php
Labels: size/XS

#33 Development
  html/index.php
Labels: approved, lgtm, size/XS

#36 Development
  html/index.php
Labels: approved

#39 Development
  html/index.php
Labels: size/XS

#40 Update index.php
  html/index.php
Labels: /final-test, size/XS
